cd extractions
bash BUILD
cd ../predictions
bash BUILD
cd ..
cd parmesan_combined
bash BUILD
cd ..
cd parmesan_combined_predictions
bash BUILD
cd ..

BUILD  extractions  parmesan_combined  parmesan_combined_predictions  parmesan_comparison  predicate_direction.txt  predictions  raw


